### PR TITLE
Feature/mail

### PR DESCRIPTION
**Pull request by susithrupasinghe**
## Purpose

Hiding mail (SMTP) credentials #<issue-number>

## Goals

1. Credentials will take as ENV Args , if not it will take default values in config 

##  Checklist
- [ ] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have performed a self-review of my own code
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Shehanka** [comment]
@susithrupasinghe can u resolve this merge conflict?

**Review by Shehanka — APPROVED** [review]
Wow! That's great 😃 Good job

**Comment by susithrupasinghe** [comment]
> Wow! That's great 😃 Good job

Thanks aiya. @ebonynon  Also thank you for your idea.

**Comment by susithrupasinghe** [comment]
> @susithrupasinghe can u resolve this merge conflict?

Done aiya :)

**Pull request merged**
